- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copying the roboshop.conf file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: copying the nginx.conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: remove the existing content in /usr/share/nginx/html/
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create the new directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: download the frontend application code
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download App Content
  ansible.builtin.unarchive:
    src: http://172.31.95.205:8081/repository/{{component}}/{{component}}-{{ lookup('aws_ssm', '{{ env }}.{{component}}.app_version', region='us-east-1' ) }}.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes # or true

- name: Import File Beat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter