- name: Add Application user
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Remove Old Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
     path: /app
     state: directory

#- name: Download the Application Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download App Content
  ansible.builtin.unarchive:
    src: http://172.31.95.205:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes
