#- name: Install Maven
#  ansible.builtin.yum:
#    name: maven
#    state: installed

#this step is no more needed as done by jenkins pipeline
- name: Install Java
  ansible.builtin.yum:
    name: java-17-openjdk
    state: installed

- name: Include app_prequesites task
  ansible.builtin.import_tasks:
    file: app_prereq.yml

#this step is no more needed as done by jenkins pipeline
#- name: Download Maven Dependencies
#  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
#  args:
#   chdir: /app

- name: Include schema_setup task
  ansible.builtin.import_tasks:
    file: schema_setup.yml  # importing task from common role

- name: Include SystemD task
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: Import Prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter