- name: configure NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include app_prereq task
  ansible.builtin.import_tasks:
    file: app_prereq.yml  # importing task from common role

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app  # changing the directory before install dependencies

- name: Include schema_setup task
  ansible.builtin.import_tasks:
    file: schema_setup.yml  # importing task from common role

- name: Include systemd_setup task
  ansible.builtin.import_tasks:
    file: systemd_setup.yml  # importing task from common role