- name: Load MongoDB Schema
  when: schema_setup == "mongo"
  block:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load MongoDB Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', '{{ env }}.{{ component }}.mongo_endpoint', region='us-east-1') }} </app/schema/{{component}}.js

- name: Load MySql Schema
  when: schema_setup == "mysql"
  block:
    - name: Copying MySql repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Install mysql client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load MySql Schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{ env }}.{{ component }}.mysqldb_host', region='us-east-1' ) }} -u{{ lookup('aws_ssm', '{{ env }}.shipping.mysqldb_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', '{{ env }}.shipping.mysqldb_password', region='us-east-1' ) }} < /app/schema/{{component}}.sql